name: Howiesyagaloo
favicon: null
layout_spectrum: 0.15388310747221112
typography_spectrum: 0.7444211489055306
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7433765309397131
  lightness: 0.6691869227215648
  saturation: 0.027326339622959495
  rhythmicContrast: 0.2812897090334445
purpose: []
