title: 'Howies YAGALOO Das Musikmagazin '
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.0625
  brandStrength: 0.4820789
  lightness: 0.875
  brandColors:
    - '#0b0100'
    - '#ffffff'
    - '#2d2f3b'
    - '#d0cece'
    - '#918f8e'
  rhythmicContrast: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: 'Howie Yagaloo '
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.56115
layout_spectrum: 0.5275689
