name: 'Howie Yagaloo '
favicon: null
layout_spectrum: 0.5275689
typography_spectrum: 0.56115
title: 'Howies YAGALOO Das Musikmagazin '
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0100'
    - '#ffffff'
    - '#2d2f3b'
    - '#d0cece'
    - '#918f8e'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
