name: 'Howie Yagaloo '
favicon: null
layout_spectrum: 0.4824561
typography_spectrum: 0.59447
title: 'Howies YAGALOO Das Musikmagazin '
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: aus Berlin!
navigation:
  - name: Facebook
    url: www.facebook.com/yagaloo.TV/
    type: external
  - name: YOUTUBE
    url: 'https://www.youtube.com/yagalooTV'
    type: external
author:
  name: Michael "HOWIE" Weiner
  email: michael.weiner@yagaloo.com
  url: 'http://www.michael-weiner.de'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ca4bd700-a094-4961-bc60-641ff4c4e05f.jpg
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: '535623766631924'
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030202'
    - '#fefefe'
    - '#5e8422'
    - '#2f44f7'
    - '#ef3228'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
